version: '3.4'

services:
  dbtest:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'evax'
      MYSQL_ROOT_PASSWORD: 'test'

  phpmyadmintest:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      PMA_HOST: db