version: '3.4'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'evax'
      MYSQL_ROOT_PASSWORD: 'mdp'
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      PMA_HOST: db